server:
  port: 8080

spring:
  application:
    name: shyam

  # ==============================
  # PostgreSQL Database
  # ==============================
  datasource:
    url: jdbc:postgresql://localhost:5473/shyam_jewellers
    username: postgres
    password: Akash@5473
    driver-class-name: org.postgresql.Driver

  # ==============================
  # Flyway Database Migration
  # ==============================
  flyway:
    enabled: true
    locations: classpath:migration

  # ==============================
  # JPA / Hibernate
  # ==============================
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}

  # ==============================
  # Gmail SMTP
  # ==============================
  mail:
    host: smtp.gmail.com
    port: 587
    username: shyamjewellersteam@gmail.com
    password: luco bccv ubqj umqy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ==============================
# Metal Rate API
# ==============================
metals:
  dev:
    api:
      url: https://api.metals.dev/v1/metal/authority
      key: OQCLYQFASGX6FXT6QIQD199T6QIQD

# ==============================
# Cloudinary
# ==============================
cloudinary:
  folder: shyam-products
  cloud_name: djaiqzoes
  api_key: 397331224838283
  api_secret: mnjrSFnVGJcZfp1PKDbr7W3bDJs

# ==============================
# JWT
# ==============================
jwt:
  secret: 12345678901234567890123456789012
  access-token-expiration-minutes: 5
  refresh-token-expiration-hours: 5