server:
  port: 8080

spring:
  application:
    name: shyam

  datasource:
    url: jdbc:postgresql://dpg-d752qefpm1nc7397agdg-a.singapore-postgres.render.com:5432/shyam_jewelleres
    username: shyam_jewelleres_user
    password: aFurVOpX895CLKOAOsz9Mv05bQF5uZzW
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: akashkumarcucek@gmail.com
    password: saeb hgyi zmvx ybam
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: redis-14888.cce179.ap-south-1-1.ec2.cloud.redislabs.com
    port: 14888
    password: DIVhQgJkVH6sHdSfr0Vx6MlzeJdYZAYQ

# ✅ IMPORTANT: spring ke bahar
cloudinary:
  cloud_name: djaiqzoes
  api_key: 397331224838283
  api_secret: mnjrSFnVGJcZfp1PKDbr7W3bDJs