spring:
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    packages-to-scan: com.shyam.controller

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  endpoint:
    health:
      show-details: always

jwt:
  secret: 12345678901234567890123456789012
  access-token-expiration-minutes: 5
  refresh-token-expiration-hours: 5

cloudinary:
  folder: shyam-products

metals:
  dev:
    api-url: https://api.metals.dev/v1/metal/authority
    api-key: ${METALS_DEV_API_KEY:default_key_for_dev}