CREATE TABLE products (
                          id BIGSERIAL PRIMARY KEY,
                          name VARCHAR(255) UNIQUE,
                          category VARCHAR(255) NOT NULL,
                          price NUMERIC(15, 2) NOT NULL,
                          discount_percentage INT,
                          weight NUMERIC(15, 2) NOT NULL,
                          material_type VARCHAR(255) NOT NULL,
                          sku_code VARCHAR(255) NOT NULL UNIQUE,
                          short_description VARCHAR(200),
                          full_description TEXT,
                          gender VARCHAR(50),
                          average_rating DOUBLE PRECISION,
                          is_available BOOLEAN,
                          quantity INT,
                          available_stock INT,
                          image_url VARCHAR(500),
                          created_by VARCHAR(255),
                          updated_by VARCHAR(255),
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);